modules-build-helper/pom.xml
modules-parent/pom.xml

Release modules-parent 1.3

---

modules-build-helper/pom.xml
modules-parent/pom.xml
pax-exam-helper/pom.xml

- pax-exam-helper 2.1.1
- modules-build-helper 2.0.0
- modules-parent 1.5

Release for v1.10

---

modules-parent/pom.xml

Move all Lifecycle Mapping Metadata to module parent pom.xml

Add PluginManagement for lifecycle-mapping

---

pax-exam-helper/pom.xml
pax-exam-helper/src/it/it-pax-exam-xprocspec/pom.xml
pax-exam-helper/src/it/it-pax-exam-xspec/pom.xml
pax-exam-helper/src/it/it-pax-exam-xspec/src/test/java/XSpecTest.java
saxon-adapter/pom.xml

This PR is part of https://github.com/daisy/pipeline/pull/503.
Depends on:

Dependencies clean up

---

pax-exam-helper/pom.xml
pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java

- order of dependency list defines start order
- read repositories from settings file
- update spiflyBundles() to latest version
- switch from forked container to native container

Various enhancements to pax-exam-helper

---

.travis.yml
modules-build-helper/pom.xml
modules-build-helper/src/it/it-pipeline-module/pom.xml
modules-build-helper/src/it/it-pipeline-module/src/it/xprocspec/test.xprocspec
modules-parent/pom.xml
modules-test-helper/pom.xml
pax-exam-helper/src/it/it-pax-exam-xprocspec/pom.xml
pax-exam-helper/src/it/it-pax-exam-xprocspec/src/test/resources/exam.properties
pax-exam-helper/src/it/it-pax-exam-xspec/pom.xml
pax-exam-helper/src/it/it-pax-exam-xspec/src/test/resources/exam.properties
pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java

Update to latest xprocspec snapshot and further reduce test boilerplate

---

pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1707

Release pax-exam-helper v2.3.1

---

modules-test-helper/pom.xml
pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1708

Release modules-test-helper v1.0.2

---

modules-parent/pom.xml
modules-test-helper/pom.xml
pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1709

Release modules-parent v1.7

---

pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1788

Release pax-exam-helper v2.3.2

---

pax-exam-helper/pom.xml
saxon-adapter/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1793

Release saxon-adapter v1.3

---

modules-test-helper/pom.xml
pax-exam-helper/pom.xml
saxon-adapter/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1794

Release modules-test-helper v1.0.3

---

modules-parent/pom.xml
modules-test-helper/pom.xml
pax-exam-helper/pom.xml
saxon-adapter/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1796

Release modules-parent v1.8

---

modules-test-helper/pom.xml
pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/1812

Release pax-exam-helper v2.4.0

---

modules-test-helper/pom.xml
pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1813

Release modules-test-helper v1.0.4

---

modules-parent/pom.xml
modules-test-helper/pom.xml
pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-1821

Release modules-parent v1.9

---

ds-to-spi/ds-to-spi-annotations-processor/pom.xml
ds-to-spi/ds-to-spi-maven-plugin/pom.xml
ds-to-spi/ds-to-spi-runtime/pom.xml
ds-to-spi/pom.xml
modules-build-helper/pom.xml
modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2043

Release ds-to-spi v1.1.0

---

modules-build-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2044

Release modules-build-helper v2.4.0

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2046

Release modules-test-helper v2.0.0

---

ds-to-spi/ds-to-spi-annotations-processor/pom.xml
ds-to-spi/ds-to-spi-maven-plugin/pom.xml
ds-to-spi/ds-to-spi-runtime/pom.xml
ds-to-spi/pom.xml
modules-build-helper/pom.xml
modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2062

Release modules-test-helper v2.1.0

---

ds-to-spi/ds-to-spi-annotations-processor/pom.xml
ds-to-spi/ds-to-spi-maven-plugin/pom.xml
ds-to-spi/ds-to-spi-runtime/pom.xml
ds-to-spi/pom.xml
modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2059

Release ds-to-spi v1.1.1

---

ds-to-spi/ds-to-spi-maven-plugin/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2068

Release ds-to-spi/ds-to-spi-maven-plugin v1.1.2

---

ds-to-spi/ds-to-spi-maven-plugin/pom.xml
modules-build-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2069

Release modules-build-helper v2.6.0

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2097

Release modules-test-helper v2.1.1

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2101

Release modules-test-helper v2.2.1

---

ds-to-spi/ds-to-spi-annotations-processor/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2111

Release ds-to-spi/ds-to-spi-annotations-processor v1.1.2

---

ds-to-spi/ds-to-spi-runtime/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2124

Release ds-to-spi/ds-to-spi-runtime v1.2.0

---

pax-exam-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2129

Release pax-exam-helper v2.5.1

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2130

Release modules-test-helper v2.2.2

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2150

Release modules-test-helper v2.2.3

---

modules-build-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2157

Release modules-build-helper v2.7.1

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2165

Release modules-test-helper v2.2.4

---

modules-test-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2177

Release modules-test-helper v2.2.5

---

modules-build-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2183

Release modules-build-helper v2.7.2

---

ds-to-spi/ds-to-spi-annotations/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2196

Release ds-to-spi/ds-to-spi-annotations v1.0.0

---

ds-to-spi/ds-to-spi-annotations-processor/pom.xml
ds-to-spi/ds-to-spi-annotations/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2198

Release ds-to-spi/ds-to-spi-annotations-processor v1.1.3

---

modules-build-helper/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2197

Release modules-build-helper v2.8.0

---

ds-to-spi/ds-to-spi-maven-plugin/pom.xml

staged: https://oss.sonatype.org/content/repositories/orgdaisy-2199

Release ds-to-spi/ds-to-spi-maven-plugin v1.1.4
